config/routes.rb
Rails.application.routes.draw do

  root "task_lists#index"
  get "signin" => "sessions#new", as: :signin
  post "signin" => "sessions#create"
  get "signout" => "sessions#destroy", as: :signout

  get "abouts" => "abouts#about", as: :abouts

  resources :task_lists do
    resources :tasks
  end

  get "/task_list/:id/completed" => "task_lists#completed", as: :completed_task

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_list
  before_save :present?

  validates :description,:assigned_to,:due_date, presence: true

  # validates :assigned_to, presence: true

  def present?
    (due_date - Date.today) >= 0
  end

end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, length: {maximum: 20}

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def about

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :ensure_current_user, :except => [:about]

  def ensure_current_user
    redirect_to signin_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_current_user

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @user = User.new(email: params[:user][:email])
      @user.errors[:base] << "Username / password is invalid"
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to signin_path
  end

end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController

  def index
    @task_lists = TaskList.order(:name)
  end

  def show
    @task_list = TaskList.find(params[:id])
  end

  def new
   @task_list = TaskList.new
  end

  def create
    @task_list = TaskList.new(name: params[:task_list][:name])
    if @task_list.save
      flash[:notice] = "Task List was created successfully!"
      @task_lists = TaskList.order(:name)
      redirect_to root_path
    else
      flash[:notice] = "Your task list could not be created."
      render :new
    end
  end

  def edit
    @task_list = TaskList.find(params[:id])
  end

  def update
    @task_list = TaskList.find(params[:id])
    if @task_list.update_attributes(name: params[:task_list][:name])
      flash[:notice] = "Task List was updated successfully!"
      redirect_to root_path
    else
      render :edit
    end
  end

  def completed
    @task_list = TaskList.find(params[:id])
  end

  def destroy
    task_list = TaskList.find(params[:id])
    task_list.destroy
    flash[:notice] = "Task List was deleted successfully!"
    redirect_to root_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @task_list = TaskList.find(params[:task_list_id])
    @tasks = @task_list.tasks.where(assigned_to: current_user.name)
  end

  def new
    @task_list = TaskList.find(params[:task_list_id])
    @task = Task.new(task_list_id: @task_list)
    @users = User.all
  end

  def create
    task = params[:task]
    new_date = params[:new_due_date].split("/")
    # binding.pry
    date = Date.new(new_date[2].to_i, new_date[0].to_i, new_date[1].to_i)
    @task = Task.new(description: params[:task][:description], due_date: date,task_list_id: params[:task_list_id].to_i, assigned_to: params[:task][:assigned_to])
    if @task.save
      flash[:notice] = "Task was created successfully!"
      redirect_to root_path
    else
      flash[:notice] = "Your task could not be created."
      @task_list = TaskList.find(params["task_list_id"])
      @users = User.all
      render :new
    end
  end

  def update #completed task
    id = params[:id]
    task_list_id = params[:task_list_id]
    task = Task.find(id)
    task.update_attributes(completed: true)
    redirect_to completed_task_path(task_list_id)
  end

  def destroy
    id = params[:id]
    task = Task.find(id)
    task.delete
    flash[:notice] = "Task was deleted successfully!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abouts/about.html.erb
<h1>About</h1>
<p>
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.
</p>

app/views/abouts/show.html.erb
<h1>About</h1>
<p>
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Practice</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="container">
    <div class="logo">
      <%= link_to "Rails Practice", root_path %>
    </div>
    <% if current_user %>
      <div class="logout">
        <%= current_user.email %> |
        <%= link_to "Logout", signout_path %>
      </div>
    <% end %>
  </div>
</header>
<main>
  <div class="container">

    <%= yield %>
  </div>
</main>
</body>
</html>

app/views/task_lists/_form.html.erb
<%= form_for task_list do |f| %>
  <div>
    <div><%= f.label "Title", { :class => 'my_label' } %></div><br>
    <div ><%= f.text_field :name, { :class => 'my_textfield' } %>
      <p class="error" id="task_list_message" ><%= task_list.errors.messages[:name].first %></p>
    </div><br>
  </div>
  <div>
    <%= f.submit message,{ :class => "my_button" }%>
  </div>
<% end %>

app/views/task_lists/completed.html.erb
<h1><%= @task_list.name %> - Completed</h1>

<% @task_list.tasks.sort_by {|task| task.due_date }.each do |task| %>
  <% if task.completed %>
    <div class="tasks">
      <div id="task-<%= task.id%>" class="left-10 pad-top-12">
        <%= task.description  %>
        (<%= (task.due_date - Date.today).to_i %> days)
        <%= link_to "Delete", [@task_list, task],{ :method => :delete, :confirm => "Really?", :class => "delete_button"} %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/task_lists/edit.html.erb
<h2 class="left-10">Edit a Task List</h2>
<p class="bg-success" id="no_task">
  <% if flash[:notice] %>
    <%= flash[:notice] %><br>
  <% end %>
</p>
<%= render :partial => 'form',
           :locals => { :task_list => @task_list, :message => "Update Task List"}
%>

app/views/task_lists/index.html.erb
<h1 style="margin-left: 5%;text-align:left;float:left;">My Lists </h1>
  <br><br>
  <%= link_to "+ Add Task List", new_task_list_path, {:style => 'float:left; margin-left: 2%;' } %>
<br style="clear:both;"/>
<p id="task_created">
  <% if flash[:notice] %>

    <br>
    <%= flash[:notice] %><br>
    <br>

  <% end %>
</p>
<% @task_lists.each do |task_list| %>
  <section class="task-list" id="task-list-<%= task_list.id %>" >
      <h2 class="item" style="margin-left: 5%;text-align:left;float:left;width: 30%;"><%= link_to task_list.name, task_list_path(task_list.id), {:style => 'margin-left: 10%; color: black;text-decoration: none;'} %></h2><br><br>
    <%= link_to "View my tasks", task_list_tasks_path(task_list.id), {:style => 'float:left; margin-left: 2%;width: 15%;' } %>
    <%= link_to "Delete", task_list, {:method => :delete, :confirm => "Really?", :style => 'width:10%; float:left;' } %>
    <%= link_to "Edit", edit_task_list_path(task_list.id), {:style => 'width:10%; float:left;' } %>
    <%= link_to "+ Add New Task", new_task_list_task_path(task_list.id), {:style => 'float:left;' } %>
    <br style="clear:both;">
    <% if task_list.tasks.length == 0 %>
      <div class="tasks" >
        <div style="text-align: center; padding-top: 12px;">
          "Nothing here to see!"
        </div>

      </div>
    <% end %>
    <% task_list.tasks.order(:due_date).each do |task| %>
      <% unless task.completed %>
      <div class="tasks">
        <div id="task-<%= task.id%>" class="left-10 pad-top-12">
          <%= task.description  %>
          (<%= (task.due_date - Date.today).to_i %> days) -
          <b><%= task.assigned_to %></b>
          <!-- example delete link from stack overflow -->
          <%#= link_to "delete", article_comment_path(@article, comment_item),
                      :method => :delete, :confirm => "Really?" %>

          <%= link_to "Delete", [task_list, task],{ :method => :delete, :confirm => "Really?", :class => "delete_button"} %>
          <%= link_to "Completed", [task_list, task], {:method => :patch, :class => "completed_button"} %>
        </div>
      </div>
        <% end %>
    <% end %>
  </section>
  <br style="clear:both;"/>

<% end %>

<!--* Done: Cannot create a task in the past-->
<!--* Done: The current_user can view tasks that have been assigned to them-->
<!--* Done: The About page should have it's own controller, which inherits from Active Record-->
<!--* Done: Display the about page without using before_action_skip-->
<!--* Done: Calendars should be done by picking date from calendar, not multiple drop down selects-->
<!--* Done:Use the same form for Edit and New Task Lists (DRY)-->
<!--* Done (tasks nested under task_list): Redo routes with resources-->
<!--* Done: When a form has errors, place the appropriate error messages next to the corresponding form input-->
<!--* Done: Drop down for assigning tasks to users should not have a default user (i.e. default is none)-->
<!--* Done: Give error message if a user is not picked-->
<!--* Done: Edit Task List form has validations-->


<!--* Add a search box to search through tasks for specific words-->
<!--* Add a filter with two calendars to filter tasks by due date-->

<!--* Only use the default resource methods (no `complete` method in your controller!)-->

<!--* Should be able to assign tasks for up to four users-->
<!--* i.e. Four dropdowns with default to blank. Error if at least one name isn't picked.-->

<!--* As current_user, I should be able to view tasks that I've created.-->

app/views/task_lists/new.html.erb
<h1 class="left-10">Add a Task List</h1>

<p class="bg-success left-10" id="no_task">
  <% if flash[:notice] %>
    <%= flash[:notice] %><br>
  <% end %>
</p>

<div id="error_message"></div>

<div id="task_list_form">
  <%= render :partial => 'form',
             :locals => { :task_list => @task_list, :message => "Create Task List"}
  %>
</div>
<hr>
<button class="clear_task_form left-10">Clear Form</button>
<br>
<hr>
<button class="event left-10">Event</button>

app/views/task_lists/show.html.erb
<section class="task-list" >
  <h2><%= @task_list.name %></h2>
  <% @task_list.tasks.sort_by {|task| task.due_date }.each do |task| %>
    <% unless task.completed %>
      <div class="tasks">
        <div id="task-<%= task.id%>" class="left-20 pad-top-12">
          <%= task.description  %>
          (<%= (task.due_date - Date.today).to_i %> days)
          <%= link_to "Delete", [@task_list, task],{ :method => :delete, :confirm => "Really?", :class => "delete_button"} %>
        </div>
      </div>
    <% end %>
  <% end %>
</section>
<br style="clear:both;"/>

app/views/tasks/index.html.erb
<h1>Tasks assigned to <%= current_user.name %></h1>
<section class="task-list" >
  <h2><%= @task_list.name %></h2>
  <% @tasks.sort_by {|task| task.due_date }.each do |task| %>
    <% unless task.completed %>
      <div class="tasks">
        <div id="task-<%= task.id%>" class="left-20 pad-top-12">
          <%= task.description  %>
          (<%= (task.due_date - Date.today).to_i %> days) -
          <b><%= task.assigned_to %></b>
          <%= link_to "Delete", [@task_list, task],{ :method => :delete, :confirm => "Really?", :class => "delete_button"} %>
        </div>
      </div>
    <% end %>
  <% end %>
</section>
<br style="clear:both;"/>

app/views/tasks/new.html.erb
<h1 class="left-10">Add a task to <%= @task_list.name %></h1>
<div id="no_task">
<% if flash[:notice] %>
  <%= flash[:notice] %><br><br>
<% end %>
</div>
<%= form_for [@task_list, @task] do |f| %>
  <div>
    <div><%= f.label :description, class: 'my_label my_input' %></div>
    <div ><%= f.text_field :description, { :class => 'my_textfield'  } %>
      <p class="error" id="task_message" ><%= @task.errors.messages[:description].first %></p>
    </div>
    <%#= f.label :due_date, "Due Date", class: 'my_label' %>
    <span class="left-10 my_label"> Due Date:</span><br>
    <input type="text" name="new_due_date" id="datepicker" class="left-10 my_input">
    <span class="error" id="new_due_date_message" ></span>
    <div class="left-10">
      <%#= f.date_select :due_date %>
    </div>
    <%= f.label :assigned_to, "Assigned to", class: 'my_label my_input' %><br>

    <div class="left-10">
      <%= f.collection_select :assigned_to, @users, :name, :name, {include_blank: true}, class: 'assigned_to' %>
      <p class="error" id="assigned_to_message" ><%= @task.errors.messages[:assigned_to].first %></p>
      <br><br>
    </div>
    <div>
      <%= f.submit "Create Task", { :class => "my_button" } %>
    </div>
  </div>
<% end %>

  <hr>
  <button class="clear_task_form left-10">Clear Form</button>